# Configurações de Conexão (SOS Viale)
db.url=jdbc:postgresql://localhost:5600/sos_viale_db
db.user=viale_user
db.password=viale_password
db.driver=org.postgresql.Driver

# Configurações de Negócio (Região de Foz/PY/AR)
moeda.padrao=BRL
cotacao.usd=5.05
cotacao.pyg=0.00068